name: build Satellite-Orbit-Pridiction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install sgp4
          python -m pip install skyfield
          
      - name: run main.py
        run: python progs/main.py